package com.codingcrew.campusconnection;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.2
//
// Created by Quasar Development at 05/10/2016
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class VQPBasicHttpBinding_ICalculator
{
    interface VQPIWcfMethod
    {
        VQPExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(VQPExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://129.118.70.18/campusconnection/Calculator.svc";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    VQPIServiceEvents callback;
    public VQPBasicHttpBinding_ICalculator(){}

    public VQPBasicHttpBinding_ICalculator (VQPIServiceEvents callback)
    {
        this.callback = callback;
    }
    public VQPBasicHttpBinding_ICalculator(VQPIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public VQPBasicHttpBinding_ICalculator(VQPIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected VQPExtendedSoapSerializationEnvelope createEnvelope()
    {
        VQPExtendedSoapSerializationEnvelope envelope= new VQPExtendedSoapSerializationEnvelope(VQPExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,VQPExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,VQPExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
       }

       return null;
    }

        
    public Double AddNumbers(final Double number1,final Double number2 ) throws java.lang.Exception
    {
        return (Double)execute(new VQPIWcfMethod()
        {
            @Override
            public VQPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              VQPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "AddNumbers");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="number1";
                __info.type=Double.class;
                __info.setValue(number1!=null?number1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="number2";
                __info.type=Double.class;
                __info.setValue(number2!=null?number2:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(VQPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("AddNumbersResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Double(j.toString());
                }
                else if (obj!= null && obj instanceof Double){
                    return (Double)obj;
                }
                return null;
            }
        },"http://tempuri.org/ICalculator/AddNumbers");
    }
    
    public android.os.AsyncTask< Void, Void, VQPOperationResult< Double>> AddNumbersAsync(final Double number1,final Double number2)
    {
        return executeAsync(new VQPFunctions.IFunc< Double>() {
            public Double Func() throws java.lang.Exception {
                return AddNumbers( number1,number2);
            }
        });
    }
    
    public Double SubstractNumbers(final Double number1,final Double number2 ) throws java.lang.Exception
    {
        return (Double)execute(new VQPIWcfMethod()
        {
            @Override
            public VQPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              VQPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SubstractNumbers");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="number1";
                __info.type=Double.class;
                __info.setValue(number1!=null?number1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="number2";
                __info.type=Double.class;
                __info.setValue(number2!=null?number2:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(VQPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("SubstractNumbersResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Double(j.toString());
                }
                else if (obj!= null && obj instanceof Double){
                    return (Double)obj;
                }
                return null;
            }
        },"http://tempuri.org/ICalculator/SubstractNumbers");
    }
    
    public android.os.AsyncTask< Void, Void, VQPOperationResult< Double>> SubstractNumbersAsync(final Double number1,final Double number2)
    {
        return executeAsync(new VQPFunctions.IFunc< Double>() {
            public Double Func() throws java.lang.Exception {
                return SubstractNumbers( number1,number2);
            }
        });
    }
    
    public String MultiplyNumbers(final String number1,final String number2 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, VQPOperationResult< String>> MultiplyNumbersAsync(final String number1,final String number2)
    {
        return executeAsync(new VQPFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return MultiplyNumbers( number1,number2);
            }
        });
    }
    
    public String DivisionNumbers(final String number1,final String number2 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, VQPOperationResult< String>> DivisionNumbersAsync(final String number1,final String number2)
    {
        return executeAsync(new VQPFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return DivisionNumbers( number1,number2);
            }
        });
    }

    
    protected java.lang.Object execute(VQPIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        VQPExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, VQPOperationResult< T>>  executeAsync(final VQPFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, VQPOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected VQPOperationResult< T> doInBackground(Void... params) {
                VQPOperationResult< T> result = new VQPOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(VQPOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,VQPExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


