package com.codingcrew.campusconnection;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.2
//
// Created by Quasar Development at 05/10/2016
//
//---------------------------------------------------



public interface VQPIServiceEvents
{
    public void Starting();
    public void Completed(VQPOperationResult result);
}
