<%@ Page Title="" Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="Accounts.aspx.cs" Inherits="DB_Interface.Accounts" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="ContentMsg" ContentPlaceHolderID="ContentPlaceHolderMessage" runat="server">
    
    <div class="alert alert-success" runat="server" id="divMsg">        
        <asp:Label ID="lblMsg" runat="server" Text="Label"></asp:Label>
    </div>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
    <asp:GridView ID="GridViewAccounts" runat="server" CssClass="table table-hover"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        SelectMethod="GridViewAccounts_GetData"
        UpdateMethod="GridViewAccounts_UpdateItem"
        DeleteMethod="GridViewAccounts_DeleteItem" 
        OnRowEditing="GridViewAccounts_RowEditing"
        OnRowCancelingEdit="GridViewAccounts_RowCancelingEdit"
        OnRowUpdating="GridViewAccounts_RowUpdating"></asp:GridView>
    
    <br />
    <br />
    <div class="pagination-centered">
        <asp:Button ID="btnGoBack" runat="server" Text="Go Back" CssClass="btn btn-success" OnClick="btnGoBack_Click" />
    </div>
</asp:Content>
