<%@ Page Title="" Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="Courses.aspx.cs" Inherits="DB_Interface.Courses" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="ContentMsg" ContentPlaceHolderID="ContentPlaceHolderMessage" runat="server">
    <div class="alert alert-success" runat="server" id="divMsg">        
        <asp:Label ID="lblMsg" runat="server" Text="Label"></asp:Label>
    </div>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="GridViewCourses" runat="server" CssClass="table table-hover"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        SelectMethod="GridViewCourses_GetData"
        UpdateMethod="GridViewCourses_UpdateItem"
        DeleteMethod="GridViewCourses_DeleteItem"
        OnRowEditing="GridViewCourses_RowEditing"
        OnRowCancelingEdit="GridViewCourses_RowCancelingEdit"
        OnRowUpdating="GridViewCourses_RowUpdating"></asp:GridView>
    <br />
    <br />
    <div class="pagination-centered">
        <div>
            <asp:Button ID="btnNewCourse" runat="server" Text="New Course" CssClass="btn btn-large" OnClick="btnNewCourse_Click" />
            <br />
            <br />
            <asp:Button ID="btnGoBack" runat="server" Text="Go Back" CssClass="btn btn-success" OnClick="btnGoBack_Click" />
        </div>
    </div>
</asp:Content>
