<%@ Page Title="" Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="Events.aspx.cs" Inherits="DB_Interface.Events" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="ContentMsg" ContentPlaceHolderID="ContentPlaceHolderMessage" runat="server">
    <div class="alert alert-success" runat="server" id="divMsg">        
        <asp:Label ID="lblMsg" runat="server" Text="Label"></asp:Label>
    </div>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="GridViewEvents" runat="server" CssClass="table table-hover"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        SelectMethod="GridViewEvents_GetData"
        UpdateMethod="GridViewEvents_UpdateItem"
        DeleteMethod="GridViewEvents_DeleteItem"
        OnRowEditing="GridViewEvents_RowEditing"
        OnRowCancelingEdit="GridViewEvents_RowCancelingEdit"
        OnRowUpdating="GridViewEvents_RowUpdating"></asp:GridView>
    <br />
    <br />
    <div class="pagination-centered">
        <div>
            <asp:Button ID="btnNewEvent" runat="server" Text="New Event" CssClass="btn btn-large" OnClick="btnNewEvent_Click" />
            <br />
            <br />
            <asp:Button ID="btnGoBack" runat="server" Text="Go Back" CssClass="btn btn-success" OnClick="btnGoBack_Click" />
        </div>
    </div>
</asp:Content>
